Repository 2TEAM-Ideality/be14-4th-Ideality-MyLocalDiary-back, pull requests merged in 2025-05, with the labels that each got.

#47 [FEAT] 팔로잉 OR 공개 계정 유저의 정보 조회 기능 구현
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Controller/MemberQueryController.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Mapper/MemberMapper.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryService.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/dto/OtherMemberInfoDTO.java
  src/main/resources/application.yml
  src/main/resources/mapper/MemberMapper.xml
Labels: 📬 API

#50 Feature/post image
  src/main/java/com/leesang/mylocaldiary/post/jpa/controller/PostController.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/service/PostService.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/service/S3Uploader.java
Labels: ✨ Feature

#51 [FEAT]Feature/notification
  src/main/java/com/leesang/mylocaldiary/follow/jpa/controller/FollowController.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/service/FollowService.java
  src/main/java/com/leesang/mylocaldiary/notification/controller/NotificationController.java
  src/main/java/com/leesang/mylocaldiary/notification/controller/TokenTestController.java
  src/main/java/com/leesang/mylocaldiary/notification/dto/NotificationResponseDTO.java
  src/main/java/com/leesang/mylocaldiary/notification/repository/NotificationRepository.java
  src/main/java/com/leesang/mylocaldiary/notification/service/NotificationService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#52 Feat 게시글 작성 페이지
  src/main/java/com/leesang/mylocaldiary/post/jpa/controller/PostController.java
  src/main/resources/application.yml
Labels: ✨ Feature

#54 [REFACTOR] refresh-token 발급 변경, 로그아웃 변경
  src/main/java/com/leesang/mylocaldiary/common/exception/ErrorCode.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/controller/MemberController.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/service/MemberService.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/service/MemberServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtFilter.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtProvider.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtUtil.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginController.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#55 feat 마이페이지 팔로우 목록 /팔로우 명수 조회/ 게시글 갯수 조회
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/FollowedUserDTO.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPageFollowController.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPageFollowMapper.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPageFollowService.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPagePostController.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPagePostMapper.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPagePostService.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/resources/mapper/mypagedetail/MyPageFollowMapper.xml
  src/main/resources/mapper/mypagedetail/MyPagePostMapper.xml
Labels: ✨ Feature

#56 [REFACOR] 쿠키 발급 변경
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationFilter.java
Labels: 🔨 Refactor

#58 fix post create 오류 고침
  src/main/java/com/leesang/mylocaldiary/post/jpa/controller/PostController.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#57 [Feat] 뱃지, 스탬프 조회 기능 구현
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/controller/StampController.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/dto/RegisterStampDTO.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/entity/MemberBadge.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/entity/MemberStamp.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/repository/MemberBadgeRepository.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/repository/MemberStampRepository.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/service/StampService.java
  src/main/java/com/leesang/mylocaldiary/stamp/jpa/service/StampServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/stamp/mybatis/controller/StampQueryController.java
  src/main/java/com/leesang/mylocaldiary/stamp/mybatis/dto/MemberStampDTO.java
  src/main/java/com/leesang/mylocaldiary/stamp/mybatis/mapper/StampMapper.java
  src/main/java/com/leesang/mylocaldiary/stamp/mybatis/service/StampQueryService.java
  src/main/java/com/leesang/mylocaldiary/stamp/mybatis/service/StampQueryServiceImpl.java
  src/main/resources/mapper/StampMapper.xml
  src/main/resources/sql/DDL.sql
  src/main/resources/sql/post_test.sql
Labels: ✨ Feature

#59 [FEAT]팔로워 조회 추가
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPageFollowController.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPageFollowMapper.java
  src/main/java/com/leesang/mylocaldiary/mypagedetail/mybatis/MyPageFollowService.java
  src/main/resources/mapper/mypagedetail/MyPageFollowMapper.xml
Labels: ✨ Feature

#64 지도 백 구현
  src/main/java/com/leesang/mylocaldiary/post/jpa/service/PostService.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/controller/PostQueryController.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/dto/PostSimpleResponse.java
  src/main/java/com/leesang/mylocaldiary/search/SearchController.java
  src/main/java/com/leesang/mylocaldiary/search/SearchService.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/secret.properties.example
  src/main/resources/sql/report_reason.sql
Labels: ✨ Feature

#67 [REFACOR] token 발급 방식 변경
  src/main/java/com/leesang/mylocaldiary/member/jpa/controller/MemberController.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/service/MemberService.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/service/MemberServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationFilter.java
Labels: 🔨 Refactor
