Repository 2TEAM-Ideality/be14-4th-Ideality-MyLocalDiary-back, pull requests merged in 2025-04, with the labels that each got.

#2 [FEAT] 회원, 장소, 사진, 게시글, 좋아요, 댓글, 장소 DDL 구문 작성 완료
  .gitignore
  my-local-diary/src/main/resources/sql/DDL.sql
Labels: ⚙ Setting, ✨ Feature

#4 [FEAT] SQL문 작성(신고,알림, 팔로우,스탬프)
  my-local-diary/src/main/resources/sql/DDL.sql
Labels: ✨ Feature

#5 [SETTING] 리팩토링 템플릿 추가
  .github/ISSUE_TEMPLATE/🔧-리팩토링.md
  .github/ISSUE_TEMPLATE/🚀-기능-개발.md
Labels: ⚙ Setting

#7 [REFACTOR] ddl 제약 조건 추가 및 뱃지, 회원 별 뱃지 테이블 추가
  my-local-diary/src/main/resources/sql/DDL.sql
Labels: 🔨 Refactor

#9 [FIX] 프로젝트 구조 변경
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  my-local-diary/settings.gradle
  settings.gradle
  src/main/java/com/leesang/mylocaldiary/MyLocalDiaryApplication.java
  src/main/java/com/leesang/mylocaldiary/member/TestController.java
  src/main/java/com/leesang/mylocaldiary/security/config/TestConfig.java
  src/main/java/com/leesang/mylocaldiary/test_jpa/TestJpaMapper.java
  src/main/java/com/leesang/mylocaldiary/test_jpa/TestJpaService.java
  src/main/java/com/leesang/mylocaldiary/test_mybatis/TestMapper.java
  src/main/java/com/leesang/mylocaldiary/test_mybatis/TestService.java
  src/main/resources/application.yml
  src/main/resources/mapper/test/TestMapper.xml
  src/main/resources/secret.properties.example
  src/main/resources/sql/DDL.sql
  src/test/java/com/leesang/mylocaldiary/MyLocalDiaryApplicationTests.java
Labels: ⚙ Setting

#10 [FEAT] S3 환경설정
  build.gradle
  src/main/java/com/leesang/mylocaldiary/s3/config/S3Config.java
  src/main/java/com/leesang/mylocaldiary/s3/config/S3Controller.java
  src/main/java/com/leesang/mylocaldiary/s3/config/S3Service.java
  src/main/resources/application.yml
  src/main/resources/secret.properties.example
Labels: ⚙ Setting

#15 [FEAT] 로그인 및 jwt token 발급 구현 완료
  build.gradle
  src/main/java/com/leesang/mylocaldiary/auth/controller/AuthController.java
  src/main/java/com/leesang/mylocaldiary/auth/dto/RequestLoginDTO.java
  src/main/java/com/leesang/mylocaldiary/common/response/CommonResponseVO.java
  src/main/java/com/leesang/mylocaldiary/member/TestController.java
  src/main/java/com/leesang/mylocaldiary/member/aggregate/MemberEntity.java
  src/main/java/com/leesang/mylocaldiary/member/repository/MemberRepository.java
  src/main/java/com/leesang/mylocaldiary/security/config/EncoderConfig.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/security/details/CustomUserDetails.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationProvider.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtProvider.java
  src/main/java/com/leesang/mylocaldiary/security/util/HMACKKeyGenerator.java
  src/main/java/com/leesang/mylocaldiary/test_jpa/TestJpaMapper.java
  src/main/java/com/leesang/mylocaldiary/test_jpa/TestJpaService.java
  src/main/java/com/leesang/mylocaldiary/test_mybatis/TestMapper.java
  src/main/java/com/leesang/mylocaldiary/test_mybatis/TestService.java
  src/main/resources/application.yml
  src/main/resources/sql/member_test_data.sql
  src/test/java/com/leesang/mylocaldiary/MyLocalDiaryApplicationTests.java
Labels: ✨ Feature

#17 [REFACTOR] ddl 변동 사항 추가 완료
  src/main/resources/sql/DDL.sql
Labels: 🔨 Refactor

#20 [Feature] 카카오 로그인 구현완료
  build.gradle
  src/main/java/com/leesang/mylocaldiary/member/aggregate/MemberEntity.java
  src/main/java/com/leesang/mylocaldiary/member/repository/MemberRepository.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginController.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginPageController.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/dto/KakaoTokenResponseDto.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/dto/KakaoUserInfoResponseDto.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/service/KakaoService.java
  src/main/resources/application.yml
  src/main/resources/secret.properties.example
Labels: ✨ Feature

#25 fix:카카오 로그인
  src/main/java/com/leesang/mylocaldiary/member/aggregate/MemberEntity.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginController.java
Labels: 🐞 BugFix

#26 chore jenkins 빌드 테스트
  .gitattributes
  .github/ISSUE_TEMPLATE/✅-테스트-케이스.md
  .github/ISSUE_TEMPLATE/🐞-버그-제보.md
  .github/ISSUE_TEMPLATE/🔧-리팩토링.md
  .github/ISSUE_TEMPLATE/🙋-질문-건의.md
  .github/ISSUE_TEMPLATE/🚀-기능-개발.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/leesang/mylocaldiary/MyLocalDiaryApplication.java
  src/main/java/com/leesang/mylocaldiary/auth/controller/AuthController.java
  src/main/java/com/leesang/mylocaldiary/auth/dto/RequestLoginDTO.java
  src/main/java/com/leesang/mylocaldiary/common/response/CommonResponseVO.java
  src/main/java/com/leesang/mylocaldiary/member/aggregate/MemberEntity.java
  src/main/java/com/leesang/mylocaldiary/member/repository/MemberRepository.java
  src/main/java/com/leesang/mylocaldiary/s3/config/S3Config.java
  src/main/java/com/leesang/mylocaldiary/s3/config/S3Controller.java
  src/main/java/com/leesang/mylocaldiary/s3/config/S3Service.java
  src/main/java/com/leesang/mylocaldiary/security/config/EncoderConfig.java
  src/main/java/com/leesang/mylocaldiary/security/config/TestConfig.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/security/details/CustomUserDetails.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationProvider.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtProvider.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginController.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginPageController.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/dto/KakaoTokenResponseDto.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/dto/KakaoUserInfoResponseDto.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/dto/LoginResponseDto.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/service/KakaoService.java
  src/main/java/com/leesang/mylocaldiary/security/util/HMACKKeyGenerator.java
  src/main/resources/application.yml
  src/main/resources/mapper/test/TestMapper.xml
  src/main/resources/secret.properties.example
  src/main/resources/sql/DDL.sql
  src/main/resources/sql/member_test_data.sql
  src/test/java/com/leesang/mylocaldiary/MyLocalDiaryApplicationTests.java
Labels: 🌏 Deploy

#13 [FEAT] 게시글 작성 기능 구현
  build.gradle
  src/main/java/com/leesang/mylocaldiary/post/jpa/controller/PostController.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/dto/PostCreateRequest.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/dto/PostResponse.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/entity/Photo.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/entity/Place.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/entity/Post.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/repository/PhotoRepository.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/repository/PlaceRepository.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/repository/PostRepository.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/service/PostService.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/service/S3Uploader.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/controller/PostQueryController.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/dto/CommentResponse.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/dto/PhotoInfo.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/dto/PlaceInfo.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/dto/PostDetailResponse.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/dto/PostSimpleResponse.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/mapper/PostMapper.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/service/PostQueryService.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/sql/DDL.sql
  src/main/resources/sql/post_test.sql
Labels: ✨ Feature

#24 [FEAT] 회원가입 기능 구현 완료
  build.gradle
  src/main/java/com/leesang/mylocaldiary/auth/controller/AuthController.java
  src/main/java/com/leesang/mylocaldiary/auth/dto/RequestEmailDTO.java
  src/main/java/com/leesang/mylocaldiary/auth/dto/RequestSignUpDTO.java
  src/main/java/com/leesang/mylocaldiary/auth/dto/RequestVerifyEmailDTO.java
  src/main/java/com/leesang/mylocaldiary/auth/service/AuthService.java
  src/main/java/com/leesang/mylocaldiary/auth/service/AuthServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/common/exception/ErrorCode.java
  src/main/java/com/leesang/mylocaldiary/common/exception/GlobalException.java
  src/main/java/com/leesang/mylocaldiary/common/exception/GlobalExceptionHandler.java
  src/main/java/com/leesang/mylocaldiary/email/service/EmailAuthService.java
  src/main/java/com/leesang/mylocaldiary/email/service/EmailSendService.java
  src/main/java/com/leesang/mylocaldiary/email/service/EmailSendServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/member/aggregate/MemberEntity.java
  src/main/java/com/leesang/mylocaldiary/redis/config/RedisConfig.java
  src/main/java/com/leesang/mylocaldiary/redis/util/RedisUtil.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationFilter.java
  src/main/resources/application.yml
  src/main/resources/secret.properties.example
  src/main/resources/sql/DDL.sql
  src/main/resources/sql/member_test_data.sql
Labels: 📬 API, ✨ Feature

#31 [FEAT] JwtFilter, JwtUtil 추가 및 회원 더미데이터 비밀번호 수정
  src/main/java/com/leesang/mylocaldiary/member/controller/MemberController.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtFilter.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtUtil.java
  src/main/resources/sql/member_test_data.sql
Labels: 📬 API, ✨ Feature

#33 [FEAT] 로그아웃, refresh token 도입
  src/main/java/com/leesang/mylocaldiary/auth/controller/AuthController.java
  src/main/java/com/leesang/mylocaldiary/auth/service/AuthServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/common/exception/ErrorCode.java
  src/main/java/com/leesang/mylocaldiary/member/controller/MemberController.java
  src/main/java/com/leesang/mylocaldiary/member/service/MemberService.java
  src/main/java/com/leesang/mylocaldiary/member/service/MemberServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtFilter.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtProvider.java
  src/main/java/com/leesang/mylocaldiary/security/jwt/JwtUtil.java
  src/main/resources/application.yml
Labels: 📬 API, ✨ Feature

#38 [Feature] 마이페이지 캘린더 구현 완료
  src/main/java/com/leesang/mylocaldiary/post/mybatis/controller/PostQueryController.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/dto/PostDateResponse.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/mapper/PostMapper.java
  src/main/java/com/leesang/mylocaldiary/post/mybatis/service/PostQueryService.java
  src/main/resources/mapper/PostMapper.xml
Labels: ✨ Feature

#39 [FEAT] 회원 더미 데이터 수정, ENUM 추가, 회원 조회 개발 완료
  src/main/java/com/leesang/mylocaldiary/auth/service/AuthServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/aggregate/MemberEntity.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/aggregate/MemberProvider.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/aggregate/MemberRole.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/aggregate/MemberStatus.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/controller/MemberController.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/repository/MemberRepository.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/service/MemberService.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/service/MemberServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Controller/MemberQueryController.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Mapper/MemberMapper.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryService.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/dto/MemberInfoDTO.java
  src/main/java/com/leesang/mylocaldiary/member/repository/MemberRepository.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/controller/PostController.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/entity/Post.java
  src/main/java/com/leesang/mylocaldiary/post/jpa/service/PostService.java
  src/main/java/com/leesang/mylocaldiary/security/details/CustomUserDetails.java
  src/main/java/com/leesang/mylocaldiary/security/filter/CustomAuthenticationProvider.java
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginController.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/sql/DDL.sql
  src/main/resources/sql/member_test_data.sql
Labels: 📬 API, ✨ Feature

#27 [완료][Feature/admin] 관리자 기본 기능 & 신고 신청 완료
  src/main/java/com/leesang/mylocaldiary/admin/aggregate/ReportEntity.java
  src/main/java/com/leesang/mylocaldiary/admin/aggregate/ReportReasonEntity.java
  src/main/java/com/leesang/mylocaldiary/admin/aggregate/ReportStatus.java
  src/main/java/com/leesang/mylocaldiary/admin/aggregate/ReportType.java
  src/main/java/com/leesang/mylocaldiary/admin/aggregate/SuspensionEntity.java
  src/main/java/com/leesang/mylocaldiary/admin/aggregate/SuspensionType.java
  src/main/java/com/leesang/mylocaldiary/admin/controller/AdminController.java
  src/main/java/com/leesang/mylocaldiary/admin/dto/ReportDTO.java
  src/main/java/com/leesang/mylocaldiary/admin/dto/ReportDetailDTO.java
  src/main/java/com/leesang/mylocaldiary/admin/dto/RequestHandleReportDTO.java
  src/main/java/com/leesang/mylocaldiary/admin/dto/RequestReportDTO.java
  src/main/java/com/leesang/mylocaldiary/admin/dto/SuspensionCreateRequestDTO.java
  src/main/java/com/leesang/mylocaldiary/admin/dto/SuspensionDTO.java
  src/main/java/com/leesang/mylocaldiary/admin/mapper/ReportMapper.java
  src/main/java/com/leesang/mylocaldiary/admin/mapper/SuspensionMapper.java
  src/main/java/com/leesang/mylocaldiary/admin/repository/ReportReasonRepository.java
  src/main/java/com/leesang/mylocaldiary/admin/repository/ReportRepository.java
  src/main/java/com/leesang/mylocaldiary/admin/repository/SuspensionRepository.java
  src/main/java/com/leesang/mylocaldiary/admin/service/AdminCommandService.java
  src/main/java/com/leesang/mylocaldiary/admin/service/AdminCommandServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/admin/service/AdminQueryService.java
  src/main/java/com/leesang/mylocaldiary/admin/service/AdminQueryServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/common/converter/ReportStatusConverter.java
  src/main/java/com/leesang/mylocaldiary/common/converter/ReportTypeConverter.java
  src/main/java/com/leesang/mylocaldiary/common/exception/ErrorCode.java
  src/main/java/com/leesang/mylocaldiary/common/response/config/typehandler/LocalDateTimeTypeHandler.java
  src/main/java/com/leesang/mylocaldiary/common/typehandler/LocalDateTimeTypeHandler.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/aggregate/MemberEntity.java
  src/main/java/com/leesang/mylocaldiary/member/jpa/aggregate/MemberStatus.java
  src/main/java/com/leesang/mylocaldiary/s3/S3Config.java
  src/main/java/com/leesang/mylocaldiary/s3/S3Controller.java
  src/main/java/com/leesang/mylocaldiary/s3/S3Service.java
  src/main/java/com/leesang/mylocaldiary/security/config/TestConfig.java
  src/main/java/com/leesang/mylocaldiary/security/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/mapper/admin/ReportMapper.xml
  src/main/resources/mapper/admin/SuspendMapper.xml
  src/main/resources/sql/DDL.sql
  src/main/resources/sql/member_test_data.sql
Labels: ✨ Feature

#40 [REFACTOR] 카카오 로그인 refresh-token 추가
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginController.java
Labels: 📬 API, ✨ Feature

#48 Test webhook 확인용 PR
  src/main/java/com/leesang/mylocaldiary/security/kakao/controller/KakaoLoginController.java
Labels: ✅ Test, 🌏 Deploy

#46 [FEAT] 실시간 팔로잉 알람 sse 통신 구현 완료
  src/main/java/com/leesang/mylocaldiary/follow/controller/FollowController.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/controller/FollowController.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/dto/FollowRequestDTO.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/entity/Follow.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/repository/FollowRepository.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/service/FollowService.java
  src/main/java/com/leesang/mylocaldiary/follow/service/FollowService.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Controller/MemberQueryController.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Mapper/MemberMapper.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryService.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/dto/SearchMemberDTO.java
  src/main/java/com/leesang/mylocaldiary/notification/controller/FollowSseController.java
  src/main/java/com/leesang/mylocaldiary/notification/service/NotificationService.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/sql/member_test_data.sql
Labels: 🐞 BugFix, ✨ Feature

#49 [Test] main 웹훅 테스트
  src/main/java/com/leesang/mylocaldiary/follow/controller/FollowController.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/controller/FollowController.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/dto/FollowRequestDTO.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/entity/Follow.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/repository/FollowRepository.java
  src/main/java/com/leesang/mylocaldiary/follow/jpa/service/FollowService.java
  src/main/java/com/leesang/mylocaldiary/follow/service/FollowService.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Controller/MemberQueryController.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Mapper/MemberMapper.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryService.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/Service/MemberQueryServiceImpl.java
  src/main/java/com/leesang/mylocaldiary/member/mybatis/dto/SearchMemberDTO.java
  src/main/java/com/leesang/mylocaldiary/notification/controller/FollowSseController.java
  src/main/java/com/leesang/mylocaldiary/notification/service/NotificationService.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/sql/member_test_data.sql
Labels: ✅ Test, 🌏 Deploy
